// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMVCNetCore.Context;

namespace TestMVCNetCore.Migrations
{
    [DbContext(typeof(TestMVCNetCoreContext))]
    partial class TestMVCNetCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestMVCNetCore.Models.Company", b =>
                {
                    b.Property<int>("Comp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Comp_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Comp_CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comp_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Comp_Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.Header", b =>
                {
                    b.Property<int>("Header_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Header_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Header_Id");

                    b.ToTable("Header");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.Header_Detail", b =>
                {
                    b.Property<int>("Header_Detail_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Header_Detail_Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Header_Detail_Estimated")
                        .HasColumnType("real");

                    b.Property<string>("Header_Detail_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Header_Detail_Quantity")
                        .HasColumnType("real");

                    b.Property<int>("Header_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Header_Id1")
                        .HasColumnType("int");

                    b.Property<int>("TypOption_Id")
                        .HasColumnType("int");

                    b.HasKey("Header_Detail_Id");

                    b.HasIndex("Header_Id1");

                    b.ToTable("Header_Detail");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.TypeOption", b =>
                {
                    b.Property<int>("TypOption_Id")
                        .HasColumnType("int");

                    b.Property<string>("TypOpt_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypOption_Id");

                    b.ToTable("TypeOption");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.UserCompany", b =>
                {
                    b.Property<int>("UserComp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Act_Id")
                        .HasColumnType("int");

                    b.Property<string>("AspNetUser_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comp_Id")
                        .HasColumnType("int");

                    b.Property<bool>("UserComp_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UserComp_CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UserComp_DisableDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserComp_Id");

                    b.ToTable("UserCompany");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.UserCompanyVM", b =>
                {
                    b.Property<int>("UserComp_Id")
                        .HasColumnType("int");

                    b.Property<int>("Act_Id")
                        .HasColumnType("int");

                    b.Property<string>("Act_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Act_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspNetUser_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Comp_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserComp_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UserComp_CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UserComp_DisableDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserComp_Id");

                    b.ToTable("UserCompanyVM");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.Header_Detail", b =>
                {
                    b.HasOne("TestMVCNetCore.Models.Header", null)
                        .WithMany("Header_Detail")
                        .HasForeignKey("Header_Id1");
                });

            modelBuilder.Entity("TestMVCNetCore.Models.Header", b =>
                {
                    b.Navigation("Header_Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
